
CSV_FILE_PATH = 'products.csv'


TELEGRAM_BOT_TOKEN = '7260581002:AAESnxsuPfEgsRmsbWx96yySXYsMD1JPCMk'
TELEGRAM_CHAT_ID = '73355156'  


LLAMA_API_URL = 'https://api.llama-api.com/v1/chat/completions'
LLAMA_API_KEY = 'LL-uC7Sw1jt1gAVToWVVLLQQMGCVN0Ab6IWWZG8Wo8aDFiF9OpV4uudDtgXqNse4i4q'

STABLE_DIFFUSION_API_URL = 'https://modelslab.com/api/v6/realtime/text2img'
STABLE_DIFFUSION_API_KEY = 'qw2k2iUrnORHdIGVfi0SqdTlG23VKVkVtreMyYUdwAebbPTTA7Op2ihBQcDP'

EXPIRY_WARNING_THRESHOLD = 3
